run:
  timeout: 3m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gofumpt
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

